#!/usr/bin/env node
/* npm run backlog — the ordered backlog view, generated from `.agent/items/`.
 *
 * There is no `.agent/backlog.md` any more. One file per item under
 * `.agent/items/`, named by its TW number, so two concurrent runs filing
 * different items never write the same path and never conflict. This script
 * is the skim: it renders the whole queue, in order, to stdout. **Its output
 * is never committed** — a committed derived file conflicts exactly as the
 * hand-written one did, which is the trap `.agent/proposals/
 * run-state-restructure.md` §4 documents for `run-state.md`.
 *
 *   npm run backlog            the whole queue, all four sections
 *   npm run backlog -- --approved   only what an implementer may act on
 *   npm run backlog:check      validate the folder (blocking, in npm run verify)
 *
 * Ordering lives in each file's `order:` field, not in line position. Lower is
 * sooner; ties break by id, so two runs that pick the same number produce a
 * stable order rather than a conflict. Numbers are spaced by 10 so an item can
 * be inserted between two others without renumbering anything.
 */
import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { ROOT } from './verify/util.mjs';

const DIR = join(ROOT, '.agent/items');
const NOTES = join(DIR, 'notes');

export const SECTIONS = [
  ['approved', 'Approved for implementation'],
  ['needs-approval', "Needs Dan's approval"],
  ['blocked', 'Blocked'],
  ['done', 'Done'],
];

/* A file is `key: value` header lines, a blank line, then the body verbatim.
 * A header value may wrap onto continuation lines, which are indented. */
function parse(text, file) {
  const lines = text.replace(/\n$/, '').split('\n');
  const split = lines.indexOf('');
  if (split < 0) throw new Error(`${file}: no blank line between header and body`);
  const head = {};
  let last = null;
  for (const line of lines.slice(0, split)) {
    const m = line.match(/^([a-z-]+): ?(.*)$/);
    if (m && !line.startsWith(' ')) { head[m[1]] = m[2]; last = m[1]; }
    else if (last) head[last] += ' ' + line.trim();
    else throw new Error(`${file}: unparsed header line ${JSON.stringify(line)}`);
  }
  return { head, body: lines.slice(split + 1), file };
}

export function load() {
  const items = readdirSync(DIR).filter((f) => f.endsWith('.md') && f !== 'README.md')
    .map((f) => ({ ...parse(readFileSync(join(DIR, f), 'utf8'), f), kind: 'item' }));
  const notes = readdirSync(NOTES).filter((f) => f.endsWith('.md'))
    .map((f) => ({ ...parse(readFileSync(join(NOTES, f), 'utf8'), `notes/${f}`), kind: 'note' }));
  const all = [...items, ...notes];
  all.sort((a, b) => (Number(a.head.order) - Number(b.head.order))
    || String(a.head.id || a.head.note).localeCompare(String(b.head.id || b.head.note)));
  return all;
}

function render(blocks, { only } = {}) {
  const out = ['# Backlog', '',
    'Generated by `npm run backlog` from `.agent/items/` — do not commit this output,',
    'and do not hand-edit it. Edit the item files. Ordered by each file\'s `order:`',
    'field. Top = next. **Only `[approved]` items may be implemented.**'];
  for (const [status, heading] of SECTIONS) {
    if (only && status !== only) continue;
    const inSection = blocks.filter((b) => b.head.status === status);
    if (!inSection.length) continue;
    out.push('', `## ${heading}`, '');
    for (const b of inSection) {
      if (b.kind === 'note') {
        out.push(`<!-- ${b.body.map((l, i) => (i ? '     ' + l : l)).join('\n')} -->`);
      } else {
        const box = b.head.status === 'done' ? 'x' : ' ';
        const tags = b.head.tags === '—' ? '' : b.head.tags + ' ';
        out.push(`- [${box}] ${tags}${b.head.id} ${b.head.title}`);
        out.push(...b.body.map((l) => (l ? '      ' + l : l)));
      }
      out.push('');
    }
    out.pop();
  }
  return out.join('\n') + '\n';
}

/* ---- checker ------------------------------------------------------------ */
const REF = /TW-(?:\d{3}|D\d+)/g;

function check(blocks) {
  const problems = [];
  const ids = new Set(blocks.filter((b) => b.kind === 'item').map((b) => b.head.id));
  const statuses = new Set(SECTIONS.map(([s]) => s));
  for (const b of blocks) {
    const where = `.agent/items/${b.file}`;
    for (const f of b.kind === 'item' ? ['id', 'title', 'status', 'tags', 'order'] : ['note', 'status', 'order']) {
      if (!b.head[f]) problems.push(`${where}: missing \`${f}:\``);
    }
    if (!statuses.has(b.head.status)) problems.push(`${where}: unknown status ${JSON.stringify(b.head.status)}`);
    if (!/^\d+$/.test(b.head.order || '')) problems.push(`${where}: order must be a whole number`);
    if (b.kind === 'item') {
      if (b.file !== `${b.head.id}.md`) problems.push(`${where}: filename does not match \`id: ${b.head.id}\``);
      if (b.head.status === 'approved' && !b.head.tags.includes('[approved]')) {
        problems.push(`${where}: status: approved without the [approved] tag`);
      }
      if (!b.body.length) problems.push(`${where}: empty body`);
    } else if (b.file !== `notes/${b.head.note}.md`) {
      problems.push(`${where}: filename does not match \`note: ${b.head.note}\``);
    }
    for (const ref of [b.head.title || '', ...b.body].join('\n').match(REF) || []) {
      if (!ids.has(ref)) problems.push(`${where}: cross-reference to ${ref}, which has no file`);
    }
  }
  return problems;
}

/* ---- main --------------------------------------------------------------- */
const argv = process.argv.slice(2);
const blocks = load();
if (argv.includes('--check')) {
  const problems = check(blocks);
  for (const p of problems) console.log(`  ${p}`);
  const counts = SECTIONS.map(([s, h]) => `${blocks.filter((b) => b.kind === 'item' && b.head.status === s).length} ${h.toLowerCase()}`);
  console.log(`backlog: ${blocks.filter((b) => b.kind === 'item').length} items (${counts.join(', ')}), `
    + `${blocks.filter((b) => b.kind === 'note').length} notes, ${problems.length} problems`);
  if (problems.length) process.exit(1);
} else if (argv.includes('--approved')) {
  process.stdout.write(render(blocks, { only: 'approved' }));
} else {
  process.stdout.write(render(blocks));
}
