import React from 'react'

// ---- Inline icon set (replaces lucide-react) ----
export const LayoutDashboard = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<rect width=\"7\" height=\"9\" x=\"3\" y=\"3\" rx=\"1\"/><rect width=\"7\" height=\"5\" x=\"14\" y=\"3\" rx=\"1\"/><rect width=\"7\" height=\"9\" x=\"14\" y=\"12\" rx=\"1\"/><rect width=\"7\" height=\"5\" x=\"3\" y=\"16\" rx=\"1\"/>"}});
export const FlaskConical = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<path d=\"M10 2v7.31\"/><path d=\"M14 9.3V1.99\"/><path d=\"M8.5 2h7\"/><path d=\"M14 9.3a6.5 6.5 0 1 1-4 0\"/><path d=\"M5.52 16h12.96\"/>"}});
export const FileBarChart2 = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<path d=\"M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z\"/><path d=\"M14 2v5h5\"/><path d=\"M8 18v-2\"/><path d=\"M12 18v-4\"/><path d=\"M16 18v-6\"/>"}});
export const ListChecks = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<path d=\"m3 17 2 2 4-4\"/><path d=\"m3 7 2 2 4-4\"/><path d=\"M13 6h8\"/><path d=\"M13 12h8\"/><path d=\"M13 18h8\"/>"}});
export const SunMedium = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<circle cx=\"12\" cy=\"12\" r=\"4\"/><path d=\"M12 3v1\"/><path d=\"M12 20v1\"/><path d=\"M3 12h1\"/><path d=\"M20 12h1\"/><path d=\"m18.36 5.64-.7.7\"/><path d=\"m6.34 17.66-.7.7\"/><path d=\"m5.64 5.64.7.7\"/><path d=\"m17.66 17.66.7.7\"/>"}});
export const StickyNote = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<path d=\"M15.5 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V8.5Z\"/><path d=\"M15 3v6h6\"/>"}});
export const Images = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<path d=\"M18 22H4a2 2 0 0 1-2-2V6\"/><path d=\"m22 13-1.3-1.3a2 2 0 0 0-3 0L12 17\"/><circle cx=\"12\" cy=\"8\" r=\"2\"/><rect width=\"16\" height=\"16\" x=\"6\" y=\"2\" rx=\"2\"/>"}});
export const Plus = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<path d=\"M5 12h14\"/><path d=\"M12 5v14\"/>"}});
export const Trash2 = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<path d=\"M3 6h18\"/><path d=\"M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6\"/><path d=\"M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2\"/><path d=\"M10 11v6\"/><path d=\"M14 11v6\"/>"}});
export const X = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<path d=\"M18 6 6 18\"/><path d=\"m6 6 12 12\"/>"}});
export const Waves = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<path d=\"M2 6c.6.5 1.2 1 2.5 1C7 7 7 5 9.5 5c2.6 0 2.4 2 5 2 1.3 0 1.9-.5 2.5-1\"/><path d=\"M2 12c.6.5 1.2 1 2.5 1 2.5 0 2.5-2 5-2 2.6 0 2.4 2 5 2 1.3 0 1.9-.5 2.5-1\"/><path d=\"M2 18c.6.5 1.2 1 2.5 1 2.5 0 2.5-2 5-2 2.6 0 2.4 2 5 2 1.3 0 1.9-.5 2.5-1\"/>"}});
export const Bell = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<path d=\"M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9\"/><path d=\"M10.3 21a1.94 1.94 0 0 0 3.4 0\"/>"}});
export const CheckCircle2 = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<circle cx=\"12\" cy=\"12\" r=\"10\"/><path d=\"m9 12 2 2 4-4\"/>"}});
export const AlertTriangle = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<path d=\"m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3\"/><path d=\"M12 9v4\"/><path d=\"M12 17h.01\"/>"}});
export const Upload = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<path d=\"M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4\"/><path d=\"M17 8l-5-5-5 5\"/><path d=\"M12 3v12\"/>"}});
export const Check = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<path d=\"M20 6 9 17l-5-5\"/>"}});
export const ArrowUp = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<path d=\"m5 12 7-7 7 7\"/><path d=\"M12 19V5\"/>"}});
export const ArrowDown = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<path d=\"M12 5v14\"/><path d=\"m19 12-7 7-7-7\"/>"}});
export const Minus = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<path d=\"M5 12h14\"/>"}});
export const RotateCcw = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<path d=\"M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8\"/><path d=\"M3 3v5h5\"/>"}});
export const ChevronDown = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<path d=\"m6 9 6 6 6-6\"/>"}});
export const ChevronUp = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<path d=\"m18 15-6-6-6 6\"/>"}});
export const Settings2 = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<path d=\"M20 7h-9\"/><path d=\"M14 17H5\"/><circle cx=\"17\" cy=\"17\" r=\"3\"/><circle cx=\"7\" cy=\"7\" r=\"3\"/>"}});
export const Save = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<path d=\"M15.2 3a2 2 0 0 1 1.4.6l3.8 3.8a2 2 0 0 1 .6 1.4V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2z\"/><path d=\"M17 21v-7a1 1 0 0 0-1-1H8a1 1 0 0 0-1 1v7\"/><path d=\"M7 3v4a1 1 0 0 0 1 1h7\"/>"}});
export const Activity = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<path d=\"M22 12h-2.48a2 2 0 0 0-1.93 1.46l-2.35 8.36a.25.25 0 0 1-.48 0L9.24 2.18a.25.25 0 0 0-.48 0l-2.35 8.36A2 2 0 0 1 4.49 12H2\"/>"}});
export const Scale = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<path d=\"m16 16 3-8 3 8c-.87.65-1.92 1-3 1s-2.13-.35-3-1\"/><path d=\"m2 16 3-8 3 8c-.87.65-1.92 1-3 1s-2.13-.35-3-1\"/><path d=\"M7 21h10\"/><path d=\"M12 3v18\"/><path d=\"M3 7h2c2 0 5-1 7-2 2 1 5 2 7 2h2\"/>"}});
export const Beaker = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<path d=\"M4.5 3h15\"/><path d=\"M6 3v16a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V3\"/><path d=\"M6 14h12\"/>"}});
export const Target = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<circle cx=\"12\" cy=\"12\" r=\"10\"/><circle cx=\"12\" cy=\"12\" r=\"6\"/><circle cx=\"12\" cy=\"12\" r=\"2\"/>"}});
export const Gauge = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<path d=\"m12 14 4-4\"/><path d=\"M3.34 19a10 10 0 1 1 17.32 0\"/>"}});
export const Calculator = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<rect width=\"16\" height=\"20\" x=\"4\" y=\"2\" rx=\"2\"/><line x1=\"8\" x2=\"16\" y1=\"6\" y2=\"6\"/><line x1=\"16\" x2=\"16\" y1=\"14\" y2=\"18\"/><path d=\"M8 10h.01\"/><path d=\"M12 10h.01\"/><path d=\"M16 10h.01\"/><path d=\"M8 14h.01\"/><path d=\"M12 14h.01\"/><path d=\"M8 18h.01\"/><path d=\"M12 18h.01\"/>"}});
export const Download = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<path d=\"M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4\"/><path d=\"M7 10l5 5 5-5\"/><path d=\"M12 15V3\"/>"}});
export const Droplets = ({size=24, color="currentColor", strokeWidth=2, className="", style={}}) => React.createElement("svg", {width:size, height:size, viewBox:"0 0 24 24", fill:"none", stroke:color, strokeWidth:strokeWidth, strokeLinecap:"round", strokeLinejoin:"round", className:className, style:style, dangerouslySetInnerHTML:{__html: "<path d=\"M7 16.3c2.2 0 4-1.83 4-4.05 0-1.16-.57-2.26-1.71-3.19S7.29 6.75 7 5.3c-.29 1.45-1.14 2.84-2.29 3.76S3 11.1 3 12.25c0 2.22 1.8 4.05 4 4.05z\"/><path d=\"M12.56 6.6A10.97 10.97 0 0 0 14 3.02c.5 2.5 2 4.9 4 6.5s3 3.5 3 5.5a6.98 6.98 0 0 1-11.91 4.97\"/>"}});
